/*
 * generated by Xtext 2.9.1
 */
package org.archware.sosadl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SosADLStandaloneSetup extends SosADLStandaloneSetupGenerated {

	def static void doSetup() {
		new SosADLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
