/*
 * generated by Xtext
 */
package org.archware.sosadl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SosADLRuntimeModule extends org.archware.sosadl.AbstractSosADLRuntimeModule {

}
